import { options, type LeafCommand } from "./registry-common.ts";

export const RUNTIME_COMMANDS: readonly LeafCommand[] = [
  {
    path: ["runtime", "start"],
    usage: "grokbox runtime start --mode observe|identity|route",
    summary: "Ensure a root-matched modeld, save desired and observe reconciliation; a new service stays foreground until signal. No adopt or autostart install.",
    arguments: [],
    options: options([
      { flags: "--mode <mode>", description: "observe, identity, or route", required: true },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: true,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "status"],
    usage: "grokbox runtime status",
    summary: "Read box-local model runtime desired state, coverage, and census.",
    arguments: [],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "services", "status"],
    usage: "grokbox runtime services status --run-root <path> --json",
    summary: "Read exact user-service registration, file/artifact matches and manager state without starting or repairing anything.",
    arguments: [], options: options([{ flags: "--run-root <path>", description: "Explicit service run root; otherwise GROKBOX_RUN_ROOT" }]),
    stdin: "none", table: false, timeout: false, destructive: false, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  ...(["install", "uninstall"] as const).map(action => ({
    path: ["runtime", "services", action],
    usage: `grokbox runtime services ${action} --run-root <path>${action === "install" ? " --release <installed-package> --node <executable> [--start]" : ""} [--expect-plan <sha256> --confirm] --json`,
    summary: action === "install" ? "Preview or confirm exact systemd user units for daemon/modeld; requires a working lingering user manager, never alters Host startup."
      : "Preview or remove only owned inactive units; does not signal processes or delete runtime data.",
    arguments: [], options: options([
      { flags: "--run-root <path>", description: "Explicit service run root; otherwise GROKBOX_RUN_ROOT" },
      ...(action === "install" ? [{ flags: "--release <path>", description: "Installed grokbox package root, not a source checkout", required: true },
        { flags: "--node <path>", description: "Exact supported Node executable", required: true },
        { flags: "--start", description: "Explicitly start the two registered services in addition to enabling boot startup" }] : []),
      { flags: "--expect-plan <sha256>", description: "Digest returned by the current preview" },
      { flags: "--confirm", description: "Commit this exact registration plan; default is read-only preview" },
    ]), stdin: "none" as const, table: false, timeout: false, destructive: true, gateway: false, streaming: false, profile: false, localOnly: true,
  })),
  {
    path: ["runtime", "storage", "status"],
    usage: "grokbox runtime storage status --json",
    summary: "Read local monitor, process-log and journal storage independently of configuration health; adoption is reported separately.",
    arguments: [], options: options([]), stdin: "none", table: false, timeout: false,
    destructive: false, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "monitor", "install"],
    usage: "grokbox runtime monitor install --run-root <path> --agents <uuid,...> [--expect-revision <sha256> --operation-id <id> --confirm]",
    summary: "Preview or explicitly initialize observation storage and configure the management Server collector; never starts a process or enables notifications.",
    arguments: [], options: options([
      { flags: "--run-root <path>", description: "Explicit owned Host runtime root", required: true },
      { flags: "--agents <uuid,...>", description: "One to 32 explicit ownership-observation Bot UUIDs; journals cover their own source events", required: true },
      { flags: "--expect-revision <sha256>", description: "Canonical configuration revision from the preview" },
      { flags: "--operation-id <id>", description: "Stable configuration operation identity" },
      { flags: "--confirm", description: "Initialize/migrate local observation storage and publish collector configuration" },
    ]), stdin: "none", table: false, timeout: false, destructive: true, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "monitor", "init"],
    usage: "grokbox runtime monitor init --confirm",
    summary: "Initialize this installation's observation database with explicit confirmation; existing data is never replaced.",
    arguments: [], options: options([{ flags: "--confirm", description: "Allow creating local observation storage", required: true }]),
    stdin: "none", table: false, timeout: false, destructive: true,
    gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "monitor", "run"],
    usage: "grokbox runtime monitor run --agents <uuid,...> --confirm [--once]",
    summary: "Explicitly collect read-only Server facts into local observations; never send messages, change identity, or adopt Host.",
    arguments: [], options: options([
      { flags: "--confirm", description: "Allow the local collector and its observation writes", required: true },
      { flags: "--agents <uuid,...>", description: "One to 32 explicit Bot UUIDs", required: true },
      { flags: "--interval-ms <n>", description: "Serial polling interval, 10000–300000 ms; default 30000" },
      { flags: "--once", description: "Commit one sample and stop" },
    ]), stdin: "none", table: false, timeout: false, destructive: true,
    gateway: false, streaming: true, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "monitor", "snapshot"],
    usage: "grokbox runtime monitor snapshot",
    summary: "Read the existing local observation snapshot; never query Server, initialize storage or start a collector.",
    arguments: [], options: options(), stdin: "none", table: false, timeout: false,
    destructive: false, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "monitor", "events"],
    usage: "grokbox runtime monitor events [--after <cursor>] [--limit <n>]",
    summary: "Read bounded local observation events without modifying storage or product state.",
    arguments: [], options: options([
      { flags: "--after <cursor>", description: "Database and collector epoch cursor" },
      { flags: "--limit <n>", description: "Page size from 1 to 200" },
    ]), stdin: "none", table: false, timeout: false,
    destructive: false, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "monitor", "incident"],
    usage: "grokbox runtime monitor incident <incident-id> [--evidence-revision <n>] [--view local-diagnostic|public-summary]",
    summary: "Read an immutable incident evidence revision without network access, collection, GC or lease renewal.",
    arguments: [{ syntax: "<incident-id>", description: "Exact local incident UUID, not a STEP ID" }],
    options: options([{ flags: "--evidence-revision <n>", description: "Exact evidence revision; defaults to latest saved revision" },
      { flags: "--view <view>", description: "local-diagnostic (default), bot-diagnostic, or public-summary" }]),
    stdin: "none", table: false, timeout: false, destructive: false, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "monitor", "capture"],
    usage: "grokbox runtime monitor capture (--incident <id> | --step <id> --agent <id> | --tray <id>) --confirm",
    summary: "Explicitly freeze already indexed local evidence; never invoke a model or recover execution.",
    arguments: [], options: options([{ flags: "--incident <id>", description: "Exact incident UUID" },
      { flags: "--step <id>", description: "Resolve an indexed STEP; requires --agent" },
      { flags: "--agent <id>", description: "Exact Agent UUID" }, { flags: "--tray <id>", description: "Resolve an indexed tray; ambiguous matches refuse" },
      { flags: "--confirm", description: "Authorize local snapshot publication" }]),
    stdin: "none", table: false, timeout: false, destructive: true, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "monitor", "evidence", "lease"],
    usage: "grokbox runtime monitor evidence lease <incident-id> --revision <n> --duration-ms <n> --confirm",
    summary: "Reserve a bounded lifetime for existing evidence; ordinary reads never extend retention.",
    arguments: [{ syntax: "<incident-id>", description: "Exact incident UUID" }],
    options: options([{ flags: "--revision <n>", description: "Exact evidence revision", required: true },
      { flags: "--duration-ms <n>", description: "Requested bounded protection duration", required: true },
      { flags: "--confirm", description: "Authorize local evidence retention" }]),
    stdin: "none", table: false, timeout: false, destructive: true, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "monitor", "incidents"],
    usage: "grokbox runtime monitor incidents [--after <cursor>] [--limit <n>]",
    summary: "Read local incidents; these are not Host tray alerts and do not authorize execution.",
    arguments: [], options: options([
      { flags: "--after <cursor>", description: "Database and collector epoch incident cursor" },
      { flags: "--limit <n>", description: "Page size from 1 to 200" },
    ]), stdin: "none", table: false, timeout: false,
    destructive: false, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "activate"],
    usage: "grokbox runtime activate --mode observe|identity|route",
    summary: "Set box-local desired runtime mode without injecting Host.",
    arguments: [],
    options: options([
      { flags: "--mode <mode>", description: "observe, identity, or route", required: true },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "deactivate"],
    usage: "grokbox runtime deactivate",
    summary: "Set desired mode to disabled; live coverage is observed by status only.",
    arguments: [],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "log"],
    usage: "grokbox runtime log [--source control|host] [--follow]",
    summary: "Read source-scoped runtime audit events without merging controller history and current Host observations.",
    arguments: [],
    options: options([
      { flags: "--follow", description: "Unsupported: fails closed; omit for a bounded event snapshot" },
      { flags: "--source <source>", description: "Event source: control (default) or host" },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: true,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "group-progress"],
    usage: "grokbox runtime group-progress <group-id>",
    summary: "Read observed member queue, execution and buffered-reply states without waking Bots.",
    arguments: [{ syntax: "<group-id>", description: "Exact group UUID" }],
    options: options(), stdin: "none", table: false, timeout: false,
    destructive: false, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "incident"],
    usage: "grokbox runtime incident <step-id> --agent <id> [--from journal|monitor]",
    summary: "Diagnose an exact STEP from bounded local evidence without Gateway, resend or repair.",
    arguments: [{ syntax: "<step-id>", description: "Exact STEP identity from the error banner" }],
    options: options([{ flags: "--agent <id>", description: "Exact Agent ID, not a mutable name" },
      { flags: "--from <source>", description: "journal (default) or an existing monitor evidence index; never initializes or polls" }]),
    stdin: "none", table: false, timeout: false, destructive: false, gateway: false,
    streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "contracts"],
    usage: "grokbox runtime contracts",
    summary: "Read Host contract-slice snapshot hashes.",
    arguments: [],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["models", "check"],
    usage: "grokbox models check",
    summary: "Validate models.json without mutating Host.",
    arguments: [],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["models", "persist-key"],
    usage: "grokbox models persist-key <provider/model> --from-pi <provider> --confirm",
    summary: "Persist one catalog model's Pi API key as a private file reference; no Host restart or assignment change.",
    arguments: [{ syntax: "<provider/model>", description: "Existing runtime catalog model id" }],
    options: options([
      { flags: "--from-pi <provider>", description: "Explicit Pi provider owning the API key; key is never passed in argv" },
      { flags: "--confirm", description: "Confirm credential persistence and this model's reference update" },
    ]),
    stdin: "none", table: false, timeout: false, destructive: false, gateway: false,
    streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "profile", "analyze"],
    usage: "grokbox runtime profile analyze --sha <sha> --out <abs> [--capability ownership-local|current-state]",
    summary: "Triage retained snapshot; missing runner still emits envelope reject ids and write next.",
    arguments: [],
    options: options([
      { flags: "--sha <sha>", description: "Retained source SHA", required: true },
      { flags: "--out <abs>", description: "Protected analysis artifact path", required: true },
      { flags: "--capability <name>", description: "Inspect a maintained ownership-local or qualified current-state upgrade against the same-source reviewed baseline" },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "profile", "observe"],
    usage: "grokbox runtime profile observe --from <host-bundle>",
    summary: "Retain Host bytes and emit exact knife-point observation without process mutation.",
    arguments: [],
    options: options([
      { flags: "--from <host-bundle>", description: "Absolute Host bundle input; retain provenance only", required: true },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "profile", "propose"],
    usage: "grokbox runtime profile propose --from <abs> --out <abs> [--against <sha>]",
    summary: "Enumerate unreviewed literal/fingerprint candidates; never publishes reviewed.json.",
    arguments: [],
    options: options([
      { flags: "--from <abs>", description: "Absolute Host bundle input", required: true },
      { flags: "--out <abs>", description: "Protected candidate artifact path", required: true },
      { flags: "--against <sha>", description: "Optional explicit baseline SHA; not auto-picked" },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "profile", "prune"],
    usage: "grokbox runtime profile prune --plan <abs> --confirm",
    summary: "Apply an observe retention plan via trash only; never bare-delete Host corpus.",
    arguments: [],
    options: options([
      { flags: "--plan <abs>", description: "Absolute retention plan JSON", required: true },
      { flags: "--confirm", description: "Required; execute the plan after digest recheck" },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: true,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "profile", "replay"],
    usage: "grokbox runtime profile replay (--sha <sha> | --all)",
    summary: "Loud SHA × slice replay against retained source and reviewed copies; never executes Host.",
    arguments: [],
    options: options([
      { flags: "--sha <sha>", description: "Replay one retained source SHA" },
      { flags: "--all", description: "Replay every retained generation; mutually exclusive with --sha" },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "profile", "status"],
    usage: "grokbox runtime profile status [--sha <sha>]",
    summary: "Read-only Host seam provenance/replay/upgrade/envelopeDrift facets; four-window patchImpact green is not envelope green.",
    arguments: [],
    options: options([
      { flags: "--sha <sha>", description: "Optional retained source SHA to highlight" },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "profile", "watch"],
    usage: "grokbox runtime profile watch --once [--from <host-bundle>]",
    summary: "One-shot Host seam watch closeout; no official upgrade RPC or adopt.",
    arguments: [],
    options: options([
      { flags: "--once", description: "Required; run one bounded pass and exit" },
      { flags: "--from <host-bundle>", description: "Optional absolute Host bundle to observe" },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "profile", "write"],
    usage: "grokbox runtime profile write (--sha <retainedSourceSha> | --from <host-bundle> --allow-unretained --confirm) [--slice-review <id...>] [--capability ownership-local|current-state --expected-reviewed-sha <sha>]",
    summary: "Atomically author a durable PatchProfile from a retained Host generation; envelope reject-on-drift. No live inject.",
    arguments: [],
    options: options([
      { flags: "--sha <retainedSourceSha>", description: "Retained source SHA; load bytes from the retain directory" },
      { flags: "--from <host-bundle>", description: "Unretained absolute Host path; requires --allow-unretained --confirm" },
      { flags: "--allow-unretained", description: "Waive retain-dir bind only; never skips envelope reject-on-drift" },
      { flags: "--confirm", description: "Required with --from --allow-unretained" },
      { flags: "--slice-review <id...>", description: "Exact rejecting envelope slice ids (windowSha/count/find.inWindow)" },
      { flags: "--capability <name>", description: "Upgrade the selected ownership-local or current-state capability and dependencies; requires --sha and an applicable baseline" },
      { flags: "--expected-reviewed-sha <sha>", description: "Required with --capability: exact baselineProfileSha256 from analysis; rejects intervening profile changes" },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "operation-recovery"],
    usage: "grokbox runtime operation-recovery [--confirm] [--restore-operation <id>]",
    summary: "Inspect controller/identity leases; explicitly recover proven stale metadata without Host signals or replay.",
    arguments: [],
    options: options([
      { flags: "--confirm", description: "Recover proven stale metadata or publish an original-operation physical restoration receipt; does not adopt or replay" },
      { flags: "--restore-operation <id>", description: "Inspect the historical restoration receipt for this exact failed operation; --confirm publishes it under recovery guards without resolving unknowns" },
    ]),
    stdin: "none", table: false, timeout: false, destructive: false, gateway: false,
    streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "re-adopt"],
    usage: "grokbox runtime re-adopt --confirm",
    summary: "Confirmed one-shot box-local re-adopt through the existing controller; observe loaded bridge afterward.",
    arguments: [],
    options: options([{ flags: "--confirm", description: "Required; perform at most one adopt attempt and exit" }]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "watchdog", "run"],
    usage: "grokbox runtime watchdog run",
    summary: "Box-local desired-state Host coordinator (no public inject).",
    arguments: [],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: true,
    profile: false,
    localOnly: true,
  },
  {
    path: ["runtime", "modeld", "replace"],
    usage: "grokbox runtime modeld replace --expect-epoch <uuid> --confirm",
    summary: "Replace one verified idle modeld with this packed build; never replay old requests.",
    arguments: [], options: options([
      { flags: "--expect-epoch <uuid>", description: "Exact running service epoch from status" },
      { flags: "--confirm", description: "Confirm graceful replacement; no Host kill or automatic request replay" },
    ]), stdin: "none", table: false, timeout: false, destructive: true, gateway: true, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "modeld", "stop"],
    usage: "grokbox runtime modeld stop --expect-epoch <uuid> --confirm",
    summary: "Gracefully stop one verified idle modeld; preserve unknown requests and durable history.",
    arguments: [], options: options([
      { flags: "--expect-epoch <uuid>", description: "Exact running service epoch from status" },
      { flags: "--confirm", description: "Confirm exact-owner stop; no Host signal, socket repair or request replay" },
    ]), stdin: "none", table: false, timeout: false, destructive: true, gateway: true, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "modeld", "status"],
    usage: "grokbox runtime modeld status",
    summary: "Read modeld liveness and execution admission/storage separately.",
    arguments: [], options: options(), stdin: "none", table: false, timeout: false,
    destructive: false, gateway: false, streaming: false, profile: false, localOnly: true,
  },
  {
    path: ["runtime", "modeld", "run"],
    usage: "grokbox runtime modeld run",
    summary: "Run the box-local model daemon with durable execution deduplication.",
    arguments: [],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: true,
    profile: false,
    localOnly: true,
  },
];
