// Independent narrow semantic oracle, not generated by the matcher or apply.
function main(host, options, turnId, emit) {
  const mainOptions = { agentId: host.getConversationId(), invocationId: turnId, clientNonce: options.clientNonce };
  return host.inference.createSession(emit, mainOptions);
}
function shouldRetryTurnAttempt(input) {
  const failed = globalThis[Symbol.for("grokbox.box-runtime.managed-failure.v1")];
  if (typeof failed === "function" && failed(input.error)) return false;
  return input.error.retry === true;
}
async function step(ctx, stateHandler, onStateUpdate) {
  const compact = globalThis[Symbol.for("grokbox.box-runtime.host-compact.v1")];
  return compact({ ctx, stateHandler, contextCheckpoint: async () => {
    if (typeof onStateUpdate !== "function") throw new Error("checkpoint_unavailable");
    await onStateUpdate(ctx, await stateHandler.computeNewStructure(ctx));
  } });
}
// Explicit externally reachable roles for this independent public oracle.
module.exports = { main, shouldRetryTurnAttempt, step };
