export const CLI_NAME = "grokbox";
export const DEFAULT_DISCOVERY_PATH = "/home/box/sand-data/gateway.json";
export const DEFAULT_TIMEOUT_MS = 10_000;
export const PROMPT_MAX_BYTES = 64 * 1024;
export const MEMORY_UPSTREAM_CAP = 1000;
export const DEFAULT_EVENT_CHANNELS = ["agents", "agent-upserted", "transcript"] as const;
export const ALLOWED_EVENT_CHANNELS = [
  "agents",
  "agent-upserted",
  "transcript",
  "memory",
  "subagents",
  "async-tasks",
] as const;

export type TargetKind = "agent" | "group";
export type TargetRole = "target" | "agent" | "group";
export type StdinPolicy = "none" | "text" | "secret";

export type ArgumentSpec = {
  syntax: string;
  description: string;
  role?: TargetRole;
  kinds?: readonly TargetKind[];
};

export type OptionSpec = {
  flags: string;
  description: string;
  required?: boolean;
};

export type LeafCommand = {
  path: readonly string[];
  usage: string;
  summary: string;
  arguments: readonly ArgumentSpec[];
  options: readonly OptionSpec[];
  stdin: StdinPolicy;
  table: boolean;
  timeout: boolean;
  destructive: boolean;
  gateway: boolean;
  streaming: boolean;
  profile?: boolean;
};

const JSON_OPTION: OptionSpec = { flags: "--json", description: "Write JSON" };
const TABLE_OPTION: OptionSpec = { flags: "--table", description: "Write a human-readable table" };
const TIMEOUT_OPTION: OptionSpec = {
  flags: "--timeout-ms <n>",
  description: "Finite operation timeout in milliseconds",
};

const PROFILE_OPTION: OptionSpec = { flags: "--profile <name>", description: "Select an existing Profile" };

export const GLOBAL_OPTIONS: readonly OptionSpec[] = [
  PROFILE_OPTION,
  JSON_OPTION,
  TABLE_OPTION,
  TIMEOUT_OPTION,
];

function options(
  extras: readonly OptionSpec[] = [],
  policy: { json?: boolean; table?: boolean; timeout?: boolean } = {},
): readonly OptionSpec[] {
  return [
    ...(policy.json === false ? [] : [JSON_OPTION]),
    ...(policy.table ? [TABLE_OPTION] : []),
    ...(policy.timeout ? [TIMEOUT_OPTION] : []),
    ...extras,
  ];
}

export const LEAF_COMMANDS: readonly LeafCommand[] = [
  {
    path: ["init"],
    usage: "grokbox init [<name>] [--local | --peer <name-or-dns>] [--bootstrap] [--admit-home-read] [--yes]",
    summary: "Inspect the environment and idempotently create or update a Profile.",
    arguments: [{ syntax: "[name]", description: "Profile to create/update (default: default)" }],
    options: options([
      { flags: "--local", description: "Select the local box" },
      { flags: "--peer <name-or-dns>", description: "Select one initialized Tailscale peer" },
      { flags: "--bootstrap", description: "Authorize missing daemon/endpoint bootstrap" },
      { flags: "--admit-home-read", description: "Explicitly add the peer home read policy" },
      { flags: "--yes", description: "Confirm a headless bootstrap mutation" },
    ]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
  },
  {
    path: ["skills", "list"],
    usage: "grokbox skills list [--json|--table]",
    summary: "List bundled skills (version-matched).",
    arguments: [],
    options: options([], { table: true }),
    stdin: "none",
    table: true,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
  },
  {
    path: ["profile", "list"],
    usage: "grokbox profile list [--json|--table]",
    summary: "List the built-in default and persisted Profiles.",
    arguments: [],
    options: options([], { table: true }),
    stdin: "none",
    table: true,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
  },
  {
    path: ["profile", "show"],
    usage: "grokbox profile show [<name>]",
    summary: "Show one resolved Profile without resolving secret values.",
    arguments: [{ syntax: "[name]", description: "Profile name" }],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
  },
  {
    path: ["profile", "use"],
    usage: "grokbox profile use <name>",
    summary: "Select an existing Profile in global config.",
    arguments: [{ syntax: "<name>", description: "Existing Profile name" }],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
  },
  {
    path: ["profile", "add"],
    usage: "grokbox profile add <name> [connection options]",
    summary: "Create one strictly validated Profile.",
    arguments: [{ syntax: "<name>", description: "New Profile name" }],
    options: options([
      { flags: "--transport <transport>", description: "auto, local, daemon, or gateway" },
      { flags: "--server-url <url>", description: "Daemon HTTPS endpoint" },
      { flags: "--daemon-token-ref <ref>", description: "Daemon env:/file:/keychain: reference" },
      { flags: "--gateway-url <url>", description: "Explicit Gateway endpoint" },
      { flags: "--gateway-token-ref <ref>", description: "Gateway env:/file:/keychain: reference" },
      { flags: "--gateway-headers-ref <ref>", description: "Gateway headers secret reference" },
      { flags: "--gateway-discovery <path>", description: "Local Gateway discovery path" },
      { flags: "--daemon-socket <path>", description: "Local daemon socket path" },
      { flags: "--ssh-host <host>", description: "Explicit bootstrap/recovery SSH host" },
      { flags: "--sandbox-access-token-ref <ref>", description: "Cursor account token reference" },
      { flags: "--keepalive-interval-ms <n>", description: "Sandbox keeper interval" },
      { flags: "--quota-source <source>", description: "Explicit quota source (cursor-web)" },
      { flags: "--quota-access-token-ref <ref>", description: "Quota-only env:/file:/keychain: token reference" },
      { flags: "--secret-stdin-file <field=path>", description: "Read one secret from stdin into a protected file" },
    ]),
    stdin: "secret",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
  },
  {
    path: ["profile", "update"],
    usage: "grokbox profile update <name> [connection options]",
    summary: "Update declared fields of one existing Profile.",
    arguments: [{ syntax: "<name>", description: "Existing Profile name" }],
    options: options([
      { flags: "--transport <transport>", description: "auto, local, daemon, or gateway" },
      { flags: "--server-url <url>", description: "Daemon HTTPS endpoint" },
      { flags: "--daemon-token-ref <ref>", description: "Daemon env:/file:/keychain: reference" },
      { flags: "--gateway-url <url>", description: "Explicit Gateway endpoint" },
      { flags: "--gateway-token-ref <ref>", description: "Gateway env:/file:/keychain: reference" },
      { flags: "--gateway-headers-ref <ref>", description: "Gateway headers secret reference" },
      { flags: "--gateway-discovery <path>", description: "Local Gateway discovery path" },
      { flags: "--daemon-socket <path>", description: "Local daemon socket path" },
      { flags: "--ssh-host <host>", description: "Explicit bootstrap/recovery SSH host" },
      { flags: "--sandbox-access-token-ref <ref>", description: "Cursor account token reference" },
      { flags: "--keepalive-interval-ms <n>", description: "Sandbox keeper interval" },
      { flags: "--quota-source <source>", description: "Explicit quota source (cursor-web)" },
      { flags: "--quota-access-token-ref <ref>", description: "Quota-only env:/file:/keychain: token reference" },
      { flags: "--secret-stdin-file <field=path>", description: "Read one secret from stdin into a protected file" },
    ]),
    stdin: "secret",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
  },
  {
    path: ["profile", "remove"],
    usage: "grokbox profile remove <name>",
    summary: "Remove one persisted non-default Profile.",
    arguments: [{ syntax: "<name>", description: "Profile name" }],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: true,
    gateway: false,
    streaming: false,
    profile: false,
  },
  {
    path: ["profile", "capabilities"],
    usage: "grokbox profile capabilities [<name>]",
    summary: "Show capabilities declared by one resolved Profile.",
    arguments: [{ syntax: "[name]", description: "Profile name" }],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
  },
  {
    path: ["skills", "get"],
    usage: "grokbox skills get <name> [--full] [--json]",
    summary: "Print a bundled skill.",
    arguments: [{ syntax: "<name>", description: "Skill name" }],
    options: options([{ flags: "--full", description: "Include generated command reference" }]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
    profile: false,
  },
  {
    path: ["daemon", "serve"],
    usage: "grokbox daemon serve [--socket <path>]",
    summary: "Run the local daemon in the foreground.",
    arguments: [],
    options: options([{ flags: "--socket <path>", description: "Override the local Unix socket" }]),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: true,
  },
  {
    path: ["daemon", "ensure"],
    usage: "grokbox daemon ensure [--bootstrap] [--admit-home-read] [--yes] [--timeout-ms <n>]",
    summary: "Verify or explicitly bootstrap the selected Profile daemon.",
    arguments: [],
    options: options([
      { flags: "--bootstrap", description: "Authorize installation, restart, mapping, and credential rotation" },
      { flags: "--admit-home-read", description: "Explicitly add the peer home read policy" },
      { flags: "--yes", description: "Confirm a headless bootstrap mutation" },
    ], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["daemon", "status"],
    usage: "grokbox daemon status [--timeout-ms <n>]",
    summary: "Read the local daemon handshake.",
    arguments: [],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["doctor"],
    usage: "grokbox doctor [--json|--table] [--timeout-ms <n>]",
    summary: "Diagnose Profile, Sandbox, tailnet, Serve, daemon, and Gateway boundaries without mutation.",
    arguments: [],
    options: options([], { table: true, timeout: true }),
    stdin: "none",
    table: true,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["quota"],
    usage: "grokbox quota [--json|--table] [--timeout-ms <n>]",
    summary: "Read one fresh sanitized quota snapshot from the explicitly configured source.",
    arguments: [],
    options: options([], { table: true, timeout: true }),
    stdin: "none",
    table: true,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["recover"],
    usage: "grokbox recover [--timeout-ms <n>]",
    summary: "Explicitly recover a configured remote Sandbox, private mapping, and installed daemon.",
    arguments: [],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: true,
    gateway: false,
    streaming: false,
  },
  {
    path: ["box", "status"],
    usage: "grokbox box status [--timeout-ms <n>]",
    summary: "Inspect Cursor Sandbox run state without waking it.",
    arguments: [],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["box", "wake"],
    usage: "grokbox box wake [--timeout-ms <n>]",
    summary: "Wake the Cursor Sandbox and verify brokered exec.",
    arguments: [],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["box", "keepalive", "run"],
    usage: "grokbox box keepalive run [--interval-ms <n>] [--timeout-ms <n>]",
    summary: "Run the external Sandbox lease keeper in the foreground.",
    arguments: [],
    options: options(
      [{ flags: "--interval-ms <n>", description: "Keeper interval in milliseconds" }],
      { timeout: true },
    ),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: true,
  },
  {
    path: ["box", "keepalive", "status"],
    usage: "grokbox box keepalive status",
    summary: "Read redacted persisted keeper state.",
    arguments: [],
    options: options(),
    stdin: "none",
    table: false,
    timeout: false,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["agents", "list"],
    usage: "grokbox agents list [--include-hidden] [--json|--table]",
    summary: "List non-group agents.",
    arguments: [],
    options: options(
      [{ flags: "--include-hidden", description: "Include sidebar-hidden agents" }],
      { table: true, timeout: true },
    ),
    stdin: "none",
    table: true,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["agents", "show"],
    usage: "grokbox agents show <agent>",
    summary: "Show one non-group agent without transcript side projections.",
    arguments: [
      { syntax: "<agent>", description: "Agent ID or unambiguous name/title", role: "agent", kinds: ["agent"] },
    ],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["agents", "create"],
    usage: "grokbox agents create --name <name> [agent attributes]",
    summary: "Create one non-group agent through the Gateway.",
    arguments: [],
    options: options(
      [
        { flags: "--name <name>", description: "Agent name", required: true },
        { flags: "--description <text>", description: "Agent persona or description" },
        { flags: "--instructions <text>", description: "Alias input for agent description" },
        { flags: "--title <title>", description: "Agent title" },
        { flags: "--avatar-shape <shape>", description: "Agent avatar shape" },
        { flags: "--avatar-color <color>", description: "Agent avatar color" },
        { flags: "--notify <on|off>", description: "Notify on agent updates" },
        { flags: "--hidden <on|off>", description: "Hide the agent from the sidebar" },
        { flags: "--nonce <uuid>", description: "Stable create nonce (UUID v4)" },
      ],
      { timeout: true },
    ),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["agents", "update"],
    usage: "grokbox agents update <agent> [agent attributes]",
    summary: "Update one non-group agent through the Gateway.",
    arguments: [
      { syntax: "<agent>", description: "Agent ID or unambiguous name/title", role: "agent", kinds: ["agent"] },
    ],
    options: options(
      [
        { flags: "--name <name>", description: "Agent name" },
        { flags: "--description <text>", description: "Agent persona or description" },
        { flags: "--instructions <text>", description: "Alias input for agent description" },
        { flags: "--title <title>", description: "Agent title" },
        { flags: "--avatar-shape <shape>", description: "Agent avatar shape" },
        { flags: "--avatar-color <color>", description: "Agent avatar color" },
        { flags: "--notify <on|off>", description: "Notify on agent updates" },
        { flags: "--hidden <on|off>", description: "Hide the agent from the sidebar" },
      ],
      { timeout: true },
    ),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["agents", "delete"],
    usage: "grokbox agents delete <agent> [--yes]",
    summary: "Delete one non-group agent after explicit confirmation.",
    arguments: [
      { syntax: "<agent>", description: "Agent ID or unambiguous name/title", role: "agent", kinds: ["agent"] },
    ],
    options: options([{ flags: "--yes", description: "Confirm deletion without prompting" }], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: true,
    gateway: true,
    streaming: false,
  },
  {
    path: ["groups", "list"],
    usage: "grokbox groups list [--include-hidden] [--json|--table]",
    summary: "List product groups.",
    arguments: [],
    options: options(
      [{ flags: "--include-hidden", description: "Include sidebar-hidden groups" }],
      { table: true, timeout: true },
    ),
    stdin: "none",
    table: true,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["groups", "show"],
    usage: "grokbox groups show <group>",
    summary: "Show one product group without transcript side projections.",
    arguments: [
      { syntax: "<group>", description: "Group ID or unambiguous name/title", role: "group", kinds: ["group"] },
    ],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["groups", "create"],
    usage: "grokbox groups create --name <name> --member <agent>...",
    summary: "Create one product group with resolved agent members.",
    arguments: [],
    options: options(
      [
        { flags: "--name <name>", description: "Group name", required: true },
        { flags: "--member <agent...>", description: "Agent IDs or unambiguous names/titles", required: true },
        { flags: "--description <text>", description: "Group description" },
        { flags: "--title <title>", description: "Group title applied after creation" },
        { flags: "--avatar-shape <shape>", description: "Group avatar shape applied after creation" },
        { flags: "--avatar-color <color>", description: "Group avatar color applied after creation" },
        { flags: "--notify <on|off>", description: "Notify on group updates" },
        { flags: "--hidden <on|off>", description: "Hide the group from the sidebar" },
      ],
      { timeout: true },
    ),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["groups", "update"],
    usage: "grokbox groups update <group> [group attributes]",
    summary: "Update one product group through the Gateway.",
    arguments: [
      { syntax: "<group>", description: "Group ID or unambiguous name/title", role: "group", kinds: ["group"] },
    ],
    options: options(
      [
        { flags: "--name <name>", description: "Group name" },
        { flags: "--description <text>", description: "Group description" },
        { flags: "--title <title>", description: "Group title" },
        { flags: "--avatar-shape <shape>", description: "Group avatar shape" },
        { flags: "--avatar-color <color>", description: "Group avatar color" },
        { flags: "--notify <on|off>", description: "Notify on group updates" },
        { flags: "--hidden <on|off>", description: "Hide the group from the sidebar" },
      ],
      { timeout: true },
    ),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["groups", "delete"],
    usage: "grokbox groups delete <group> [--yes]",
    summary: "Delete one product group after explicit confirmation.",
    arguments: [
      { syntax: "<group>", description: "Group ID or unambiguous name/title", role: "group", kinds: ["group"] },
    ],
    options: options([{ flags: "--yes", description: "Confirm deletion without prompting" }], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: true,
    gateway: true,
    streaming: false,
  },
  {
    path: ["groups", "members", "list"],
    usage: "grokbox groups members list <group>",
    summary: "List the current members of one product group.",
    arguments: [
      { syntax: "<group>", description: "Group ID or unambiguous name/title", role: "group", kinds: ["group"] },
    ],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["groups", "members", "add"],
    usage: "grokbox groups members add <group> <agent>",
    summary: "Add one non-group agent to a product group.",
    arguments: [
      { syntax: "<group>", description: "Group ID or unambiguous name/title", role: "group", kinds: ["group"] },
      { syntax: "<agent>", description: "Agent ID or unambiguous name/title", role: "agent", kinds: ["agent"] },
    ],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["groups", "members", "remove"],
    usage: "grokbox groups members remove <group> <agent>",
    summary: "Remove one non-group agent from a product group.",
    arguments: [
      { syntax: "<group>", description: "Group ID or unambiguous name/title", role: "group", kinds: ["group"] },
      { syntax: "<agent>", description: "Agent ID or unambiguous name/title", role: "agent", kinds: ["agent"] },
    ],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["groups", "members", "set"],
    usage: "grokbox groups members set <group> --member <agent>...",
    summary: "Replace a product group's members with resolved non-group agents.",
    arguments: [
      { syntax: "<group>", description: "Group ID or unambiguous name/title", role: "group", kinds: ["group"] },
    ],
    options: options(
      [{ flags: "--member <agent...>", description: "Agent IDs or unambiguous names/titles", required: true }],
      { timeout: true },
    ),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["send"],
    usage: "grokbox send <target> [--text <text> | stdin] [--expect-kind agent|group] [--nonce <uuid>]",
    summary: "Send one Human message via sendPrompt.",
    arguments: [
      {
        syntax: "<target>",
        description: "Agent/group ID or unambiguous name/title",
        role: "target",
        kinds: ["agent", "group"],
      },
    ],
    options: options(
      [
        { flags: "--text <text>", description: "Prompt text; suppresses stdin reads" },
        { flags: "--expect-kind <kind>", description: "Require agent or group" },
        { flags: "--nonce <uuid>", description: "Stable client nonce (UUID v4)" },
      ],
      { timeout: true },
    ),
    stdin: "text",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["history", "search"],
    usage: "grokbox history search <query> [--limit <1..100>]",
    summary: "Search transcript messages via searchAgents.",
    arguments: [{ syntax: "<query>", description: "Transcript search query" }],
    options: options([{ flags: "--limit <n>", description: "Maximum matches (1..100)" }], {
      timeout: true,
    }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["history", "tail"],
    usage: "grokbox history tail <target> [--limit <1..200>] [--before-seq <n>]",
    summary: "Read display transcript tail.",
    arguments: [
      {
        syntax: "<target>",
        description: "Agent/group ID or unambiguous name/title",
        role: "target",
        kinds: ["agent", "group"],
      },
    ],
    options: options(
      [
        { flags: "--limit <n>", description: "Entry limit (1..200)" },
        { flags: "--before-seq <n>", description: "Page backward from this sequence" },
      ],
      { timeout: true },
    ),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["history", "thread"],
    usage: "grokbox history thread <target> --root <entry-id>",
    summary: "Read one display thread.",
    arguments: [
      {
        syntax: "<target>",
        description: "Agent/group ID or unambiguous name/title",
        role: "target",
        kinds: ["agent", "group"],
      },
    ],
    options: options(
      [{ flags: "--root <entry-id>", description: "Thread root entry ID", required: true }],
      { timeout: true },
    ),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["memory", "list"],
    usage: "grokbox memory list <agent> [--limit <1..1000>] [--content]",
    summary: "List agent-scope Memory metadata.",
    arguments: [
      { syntax: "<agent>", description: "Agent ID or unambiguous name/title", role: "agent", kinds: ["agent"] },
    ],
    options: options(
      [
        { flags: "--limit <n>", description: "Local slice (1..1000)" },
        { flags: "--content", description: "Include Memory content" },
      ],
      { timeout: true },
    ),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
  {
    path: ["fs", "stat"],
    usage: "grokbox fs stat <remote-path> [--json|--table] [--timeout-ms <n>]",
    summary: "Inspect one authorized remote filesystem entry.",
    arguments: [{ syntax: "<remote-path>", description: "Named-root path (root:/relative/path)" }],
    options: options([], { table: true, timeout: true }),
    stdin: "none",
    table: true,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["fs", "list"],
    usage: "grokbox fs list <remote-path> [--json|--table] [--timeout-ms <n>]",
    summary: "List one authorized remote directory.",
    arguments: [{ syntax: "<remote-path>", description: "Named-root path (root:/relative/path)" }],
    options: options([], { table: true, timeout: true }),
    stdin: "none",
    table: true,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["fs", "read"],
    usage: "grokbox fs read <remote-path> [--json] [--timeout-ms <n>]",
    summary: "Read one bounded authorized text or binary file.",
    arguments: [{ syntax: "<remote-path>", description: "Named-root path (root:/relative/path)" }],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["fs", "download"],
    usage: "grokbox fs download <remote-path> <local-path> [--json] [--timeout-ms <n>]",
    summary: "Download and SHA-256 verify one authorized remote file.",
    arguments: [
      { syntax: "<remote-path>", description: "Named-root path (root:/relative/path)" },
      { syntax: "<local-path>", description: "New local destination path" },
    ],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: true,
  },
  {
    path: ["fs", "write"],
    usage: "grokbox fs write <remote-path> [--text <text>] [--expected-sha256 <hex>] [--json] [--timeout-ms <n>]",
    summary: "Atomically write bounded UTF-8 content to an authorized remote file.",
    arguments: [{ syntax: "<remote-path>", description: "Named-root path (root:/relative/path)" }],
    options: options([
      { flags: "--text <text>", description: "Explicit UTF-8 content; suppresses stdin reads" },
      { flags: "--expected-sha256 <hex>", description: "Replace only when current content matches SHA-256" },
    ], { timeout: true }),
    stdin: "text",
    table: false,
    timeout: true,
    destructive: true,
    gateway: false,
    streaming: false,
  },
  {
    path: ["fs", "mkdir"],
    usage: "grokbox fs mkdir <remote-path> [--json] [--timeout-ms <n>]",
    summary: "Create one authorized remote directory without implicit parents.",
    arguments: [{ syntax: "<remote-path>", description: "Named-root path (root:/relative/path)" }],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["fs", "upload"],
    usage: "grokbox fs upload <local-path> <remote-path> [--expected-sha256 <hex>] [--json] [--timeout-ms <n>]",
    summary: "Upload and atomically commit one bounded SHA-256 verified file.",
    arguments: [
      { syntax: "<local-path>", description: "Local regular-file source" },
      { syntax: "<remote-path>", description: "Named-root path (root:/relative/path)" },
    ],
    options: options([
      { flags: "--expected-sha256 <hex>", description: "Replace only when current content matches SHA-256" },
    ], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: true,
    gateway: false,
    streaming: true,
  },
  {
    path: ["fs", "remove"],
    usage: "grokbox fs remove <remote-path> [--recursive] [--yes] [--json] [--timeout-ms <n>]",
    summary: "Move an authorized remote path into recoverable root-local trash.",
    arguments: [{ syntax: "<remote-path>", description: "Named-root path (root:/relative/path)" }],
    options: options([
      { flags: "--recursive", description: "Trash a non-empty directory with elevated root policy" },
      { flags: "--yes", description: "Confirm removal in non-interactive mode" },
    ], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: true,
    gateway: false,
    streaming: false,
  },
  {
    path: ["exec", "run"],
    usage: "grokbox exec run [options] -- <argv...>",
    summary: "Submit structured argv as a durable daemon Job.",
    arguments: [{ syntax: "<argv...>", description: "Executable alias and literal arguments" }],
    options: options([
      { flags: "--cwd <root:/path>", description: "Authorized named-root working directory" },
      { flags: "--env <NAME=value...>", description: "Allowlisted environment addition" },
      { flags: "--run-timeout-ms <n>", description: "Hard process lifetime in milliseconds" },
      { flags: "--output <capture|discard>", description: "Bounded output policy" },
      { flags: "--detach", description: "Return after durable submission" },
      { flags: "--shell", description: "Use separately authorized shell execution" },
    ], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: true,
    gateway: false,
    streaming: false,
  },
  {
    path: ["jobs", "list"],
    usage: "grokbox jobs list [--state <csv>] [--limit <n>] [--json|--table] [--timeout-ms <n>]",
    summary: "List durable daemon Jobs.",
    arguments: [],
    options: options([
      { flags: "--state <csv>", description: "Filter by Job state" },
      { flags: "--limit <n>", description: "Maximum Jobs to return" },
    ], { table: true, timeout: true }),
    stdin: "none", table: true, timeout: true, destructive: false, gateway: false, streaming: false,
  },
  {
    path: ["jobs", "show"],
    usage: "grokbox jobs show <job-id> [--json] [--timeout-ms <n>]",
    summary: "Show one durable Job projection.",
    arguments: [{ syntax: "<job-id>", description: "Job identity" }],
    options: options([], { timeout: true }),
    stdin: "none", table: false, timeout: true, destructive: false, gateway: false, streaming: false,
  },
  {
    path: ["jobs", "logs"],
    usage: "grokbox jobs logs <job-id> [--offset <n>] [--limit-bytes <n>] [--follow] [--timeout-ms <n>]",
    summary: "Read bounded binary-safe Job log events as NDJSON.",
    arguments: [{ syntax: "<job-id>", description: "Job identity" }],
    options: options([
      { flags: "--offset <n>", description: "Exact log record cursor" },
      { flags: "--limit-bytes <n>", description: "Maximum decoded bytes per page" },
      { flags: "--follow", description: "Long-poll until Job logs are complete" },
    ], { json: false, timeout: true }),
    stdin: "none", table: false, timeout: true, destructive: false, gateway: false, streaming: true,
  },
  {
    path: ["jobs", "cancel"],
    usage: "grokbox jobs cancel <job-id> [--json] [--timeout-ms <n>]",
    summary: "Idempotently cancel a queued or running Job.",
    arguments: [{ syntax: "<job-id>", description: "Job identity" }],
    options: options([], { timeout: true }),
    stdin: "none", table: false, timeout: true, destructive: true, gateway: false, streaming: false,
  },
  {
    path: ["desktop", "status"],
    usage: "grokbox desktop status [--json|--table] [--timeout-ms <n>]",
    summary: "Classify seated desktop forks as lit, idle, or protected.",
    arguments: [],
    options: options([], { table: true, timeout: true }),
    stdin: "none",
    table: true,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["desktop", "keep", "add"],
    usage: "grokbox desktop keep add <agent> [--json] [--timeout-ms <n>]",
    summary: "Persist an agent id whose Chrome profile must survive prune.",
    arguments: [{ syntax: "<agent>", description: "Agent ID or unambiguous seated name", role: "agent", kinds: ["agent"] }],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["desktop", "keep", "remove"],
    usage: "grokbox desktop keep remove <agent> --yes [--json] [--timeout-ms <n>]",
    summary: "Remove a non-floor agent from the box daemon keep list.",
    arguments: [{ syntax: "<agent>", description: "Agent ID or unambiguous seated name", role: "agent", kinds: ["agent"] }],
    options: options([{ flags: "--yes", description: "Confirm removing Chrome keep protection" }], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: true,
    gateway: false,
    streaming: false,
  },
  {
    path: ["desktop", "prune", "run"],
    usage: "grokbox desktop prune run [--yes] [--json|--table] [--timeout-ms <n>]",
    summary: "Plan or stop idle unprotected forks; --yes calls official stop-window and deletes that display's Chrome profile.",
    arguments: [],
    options: options([{ flags: "--yes", description: "Execute stop-window; deletes chrome-profile-N. Default is dry-run" }], { table: true, timeout: true }),
    stdin: "none",
    table: true,
    timeout: true,
    destructive: true,
    gateway: false,
    streaming: false,
  },
  {
    path: ["desktop", "prune", "enable"],
    usage: "grokbox desktop prune enable [--json] [--timeout-ms <n>]",
    summary: "Enable the daemon idle-desktop prune tick. Each stop deletes that fork's Chrome profile.",
    arguments: [],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: true,
    gateway: false,
    streaming: false,
  },
  {
    path: ["desktop", "prune", "disable"],
    usage: "grokbox desktop prune disable [--json] [--timeout-ms <n>]",
    summary: "Disable the daemon idle-desktop prune tick.",
    arguments: [],
    options: options([], { timeout: true }),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: false,
    streaming: false,
  },
  {
    path: ["events"],
    usage: "grokbox events [--sources <csv>] [--channels <csv>] [--cursor <cursor>] [--limit <n>] [--once] [--include-memory-content]",
    summary: "Follow unified Gateway, Job, and daemon lifecycle events (NDJSON).",
    arguments: [],
    options: options(
      [
        { flags: "--sources <csv>", description: "Event source subset" },
        { flags: "--channels <csv>", description: "Allowed Gateway channel subset" },
        { flags: "--cursor <cursor>", description: "Resume from an exact daemon event cursor" },
        { flags: "--limit <n>", description: "Maximum events per daemon page" },
        { flags: "--once", description: "Exit after the first allowed event" },
        { flags: "--include-memory-content", description: "Keep memory event content" },
      ],
      { json: false, timeout: true },
    ),
    stdin: "none",
    table: false,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: true,
  },
  {
    path: ["is", "running"],
    usage: "grokbox is running <target> [--json|--table]",
    summary: "Read one roster row's running projection.",
    arguments: [
      {
        syntax: "<target>",
        description: "Agent/group ID or unambiguous name/title",
        role: "target",
        kinds: ["agent", "group"],
      },
    ],
    options: options([], { table: true, timeout: true }),
    stdin: "none",
    table: true,
    timeout: true,
    destructive: false,
    gateway: true,
    streaming: false,
  },
];

export const TOP_LEVEL_COMMANDS = [
  ...new Set(LEAF_COMMANDS.map((leaf) => leaf.path[0]).filter((name): name is string => Boolean(name))),
] as const;

export type TopLevelCommand = (typeof TOP_LEVEL_COMMANDS)[number];

export const START_HERE = `Start here (for Agents):\n  grokbox skills get core --full`;

export const EXAMPLES = [
  "grokbox skills get core --full",
  "grokbox doctor",
  "grokbox recover",
  "grokbox box status",
  "grokbox box wake",
  "grokbox box keepalive status",
  "grokbox agents list --table",
  "grokbox groups list --table",
  'grokbox history search "deployment status" --limit 10',
  'grokbox send alpha --expect-kind agent --text "hello"',
  "printf '%s' 'summarize the current blockers' | grokbox send ops --expect-kind group",
  "grokbox history tail <agent-id> --limit 50",
  "grokbox history thread <agent-id> --root <entry-id>",
  "grokbox memory list <agent-id> --limit 100",
  "grokbox events",
  "grokbox is running <agent-id>",
];

export function leafKey(path: readonly string[]): string {
  return path.join(" ");
}

export function renderCommandReference(cliVersion: string): string {
  const lines: string[] = [
    "# grokbox command reference",
    "",
    `CLI version: ${cliVersion}`,
    "",
    `Top-level names: ${TOP_LEVEL_COMMANDS.join(", ")}.`,
    "There is no raw / api fallback. Unknown names are local usage errors.",
    "",
    "## Leaf commands",
    "",
  ];
  for (const leaf of LEAF_COMMANDS) {
    lines.push(`### \`${leafKey(leaf.path)}\``, "", "```text", leaf.usage, "```", "", leaf.summary, "");
    lines.push(`- target: ${leaf.arguments.find((arg) => arg.role)?.role ?? "none"}`);
    lines.push(`- options: ${leaf.options.map((option) => option.flags).join(", ") || "none"}`);
    lines.push(`- table: ${leaf.table ? "yes" : "no"}`);
    lines.push(`- timeout: ${leaf.timeout ? "yes" : "no"}`);
    lines.push(`- stdin: ${leaf.stdin}`);
    lines.push(`- destructive: ${leaf.destructive ? "yes" : "no"}`);
    lines.push(`- gateway: ${leaf.gateway ? "yes" : "no"}`);
    lines.push(`- streaming: ${leaf.streaming ? "yes" : "no"}`, "");
  }
  lines.push("## Copy-paste", "", "```bash", ...EXAMPLES, "```", "");
  lines.push("Do not pass `--token`, `--gateway-url`, `--host`, or `--port`.");
  lines.push("Reuse `--nonce` when retrying the same send.", "");
  return lines.join("\n");
}

export const GATEWAY_METHODS = [
  "listAgents",
  "searchAgents",
  "getAgentTranscriptTail",
  "getAgentThread",
  "getAgentMemories",
  "sendPrompt",
  "createAgent",
  "createGroup",
  "updateAgent",
  "setGroupMembers",
  "setAgentNotifyOnUpdates",
  "setAgentHiddenFromSidebar",
  "deleteAgent",
] as const;

export type GatewayMethod = (typeof GATEWAY_METHODS)[number];
