export {
  STUB_ECHO_MODEL,
  STUB_ECHO_MODEL_ID,
  applyReset,
  applyUse,
  assignedModelAliases,
  assignedModelTokens,
  assertResetAllowed,
  assertRouteAssignment,
  assertStubOnlyRouteAssignments,
  assignmentTarget,
  decideRouteSession,
  disclosure,
  openaiCompatibleAdmitted,
  parseApiKeyRef,
  parseDesiredFile,
  parseModelId,
  parseModelsFile,
  persistModelsDocument,
  resolveExternalCatalog,
  resolveModelsWithPi,
  qualifiedContextWindowTokens,
  requireModel,
  resolveAssignment,
  resolveRouteSessionModel,
  routeHasNonStubAssignment,
  routeModelAdmitted,
  backendKindForModel,
  modelForAgent,
  MODEL_ALIAS_PATTERN,
  type BackendKind,
  type DesiredFile,
  type DesiredMode,
  type ModelCapabilities,
  type ModelRecord,
  type ModelsFile,
  type RouteSessionDecision,
} from "./internal/selection/models.ts";
export {
  catalogWantsPi,
  piModelsPathCandidates,
  type ExternalCatalogEntry,
} from "./internal/selection/pi-catalog.ts";
export { captureManagedSelection, computeSelectionRevision, type CapturedSelection } from "./internal/selection/selection-revision.ts";
