export {
  STUB_ECHO_MODEL,
  STUB_ECHO_MODEL_ID,
  applyReset,
  applyUse,
  applyFollowDefault,
  applyModelDelete,
  applyModelRecord,
  modelReferences,
  assignmentForBot,
  assignedReasoningEfforts,
  resolveModelSelection,
  parseResolvedModelSelection,
  type ModelAssignment,
  type BotModelAssignment,
  type ResolvedModelSelection,
  assignedModelAliases,
  assignedModelTokens,
  assertRouteAssignment,
  assertStubOnlyRouteAssignments,
  assignmentTarget,
  decideRouteSession,
  disclosure,
  ROUTE_MODEL_NOT_ADMITTED_FAILURE_CODE,
  ROUTE_MODEL_NOT_ADMITTED_MESSAGE,
  openaiCompatibleAdmitted,
  parseApiKeyRef,
  parseDesiredFile,
  parseModelId,
  parseModelsFile,
  persistModelsDocument,
  resolveExternalCatalog,
  resolveModelsWithPi,
  qualifiedContextWindowTokens,
  requireModel,
  resolveAssignment,
  resolveRouteSessionModel,
  routeHasNonStubAssignment,
  routeModelAdmitted,
  backendKindForModel,
  modelForAgent,
  MODEL_ALIAS_PATTERN,
  type BackendKind,
  type DesiredFile,
  type DesiredMode,
  type ModelCapabilities,
  type ModelRecord,
  type ModelsFile,
  type RouteSessionDecision,
} from "./internal/selection/models.ts";
export {
  catalogWantsPi,
  lookupPiProviderApiKey,
  PI_PROVIDER_NAME_PATTERN,
  PI_PROVIDER_REF_PREFIX,
  piModelsPathCandidates,
  piProviderApiKeyRef,
  type ExternalCatalogEntry,
  type PiProviderApiKeyLookup,
} from "./internal/selection/pi-catalog.ts";
export { captureManagedSelection, computeSelectionRevision, type CapturedSelection } from "./internal/selection/selection-revision.ts";
export { REASONING_EFFORTS, isReasoningEffort, parseRequestedEffort, parseReasoningPolicy, parseReasoningCapability, assertReasoningSupported, type ReasoningPolicy, type ReasoningCapability, type ReasoningEffort } from "./internal/selection/reasoning.ts";
